plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 8

Style/RedundantFetchBlock:
  Exclude:
    - 'spec/lib/ruby_gems/cache_spec.rb'
